const movies = [
  {
    id: 1,
    title: 'Inception',
    director: 'Christopher Nolan',
    year: 2010,
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    reviews: 'Outstanding',
    duration: '2h 28min',
    price: 4.99,
    buyPrice: 14.99,
    availability: 5,
    imageUrl: 'https://via.placeholder.com/150/0000FF/808080?Text=Inception',
    videoId: '8hP9D6kZseM'
  },
  {
    id: 2,
    title: 'The Matrix',
    director: 'The Wachowskis',
    year: 1999,
    synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    reviews: 'Amazing',
    duration: '2h 16min',
    price: 3.99,
    buyPrice: 12.99,
    availability: 3,
    imageUrl: 'https://via.placeholder.com/150/FF0000/FFFFFF?Text=TheMatrix',
    videoId: 'vKQi3bBA1y8'
  },
  {
    id: 3,
    title: 'Interstellar',
    director: 'Christopher Nolan',
    year: 2014,
    synopsis: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    reviews: 'Incredible',
    duration: '2h 49min',
    price: 5.99,
    buyPrice: 16.99,
    availability: 4,
    imageUrl: 'https://via.placeholder.com/150/00FF00/000000?Text=Interstellar',
    videoId: 'zSWdZVtXT7E'
  },
  {
    id: 4,
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    year: 2008,
    synopsis: 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
    reviews: 'Outstanding',
    duration: '2h 32min',
    price: 4.49,
    buyPrice: 13.49,
    availability: 2,
    imageUrl: 'https://via.placeholder.com/150/FFFF00/000000?Text=TheDarkKnight',
    videoId: 'EXeTwQWrcwY'
  },
  {
    id: 5,
    title: 'Fight Club',
    director: 'David Fincher',
    year: 1999,
    synopsis: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    reviews: 'Amazing',
    duration: '2h 19min',
    price: 6.99,
    buyPrice: 18.99,
    availability: 1,
    imageUrl: 'https://via.placeholder.com/150/FFA500/000000?Text=FightClub',
    videoId: 'SUXWAEX2jlg'
  },
  {
    id: 6,
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    year: 1994,
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    reviews: 'Amazing',
    duration: '2h 34min',
    price: 3.99,
    buyPrice: 11.99,
    availability: 5,
    imageUrl: 'https://via.placeholder.com/150/800080/FFFFFF?Text=PulpFiction',
    videoId: 's7EdQ4FqbhY'
  },
  {
    id: 7,
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    year: 1994,
    synopsis: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
    reviews: 'Heartwarming',
    duration: '2h 22min',
    price: 4.99,
    buyPrice: 15.99,
    availability: 4,
    imageUrl: 'https://via.placeholder.com/150/008080/FFFFFF?Text=ForrestGump',
    videoId: 'bLvqoHBptjg'
  },
  {
    id: 8,
    title: 'Gladiator',
    director: 'Ridley Scott',
    year: 2000,
    synopsis: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    reviews: 'Epic',
    duration: '2h 35min',
    price: 2.99,
    buyPrice: 10.99,
    availability: 2,
    imageUrl: 'https://via.placeholder.com/150/0000FF/FFFFFF?Text=Gladiator',
    videoId: 'owK1qxDselE'
  },
  {
    id: 9,
    title: 'The Shawshank Redemption',
    director: 'Frank Darabont',
    year: 1994,
    synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    reviews: 'Outstanding',
    duration: '2h 22min',
    price: 5.49,
    buyPrice: 14.99,
    availability: 3,
    imageUrl: 'https://via.placeholder.com/150/FF0000/000000?Text=Shawshank',
    videoId: '6hB3S9bIaco'
  },
  {
    id: 10,
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    year: 1972,
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    reviews: 'Masterpiece',
    duration: '2h 55min',
    price: 6.49,
    buyPrice: 19.99,
    availability: 1,
    imageUrl: 'https://via.placeholder.com/150/FFFF00/000000?Text=Godfather',
    videoId: 'sY1S34973zA'
  }
];

export default movies;
